name: protein-reference-free-analysis
channels:
  - conda-forge
dependencies:
  # Core stack
  - python=3.11
  - build
  - bump2version
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - mamba
  - pip
  - twine
  # Standard PyData stack
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - jax
  - jaxlib
  # Utilities
  - pyprojroot
  - python-dotenv
  # CLI development
  - typer
  - typer-cli
  # Software testing
  - hypothesis
  - pytest
  # Code Style Tools
  - black
  - darglint
  - flake8
  - interrogate
  - pre-commit
  - pylint
  # Documentation
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  # pip dependencies
  - pip:
      # Place packages that cannot be installed by conda in this section.
      - mknotebooks
